/** ID string generated by crypto.randomUUID()  */

export type UUID = string;

/** CSS-valid color string */

export type Color = string;

/** Smallest Monetary Unit, eg. cents */

export type SMU = number;

export interface User {
    id: UUID;
    name: string;
    color?: Color;
}


export interface ExpenseCategory {
    id: UUID;
    name: string;
    description?: string;
    color?: Color;
}


export interface Expense {
    id: UUID;
    date: Date;
    amount: SMU;
    payer: User;
    title: string;
    description?: string;
    /** Users for splitting the bill, if undefined then for all */
    for?: Array<User>;
}

export {};